site_name: Python Monster
site_url: https://zamaniamin.github.io/python/
repo_url: https://github.com/zamaniamin/python
repo_name: zamaniamin/python

theme:
  name: material
  #  favicon: images/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    #    - navigation.top
    - navigation.tabs
    - navigation.path
    - content.code.copy
    #    - navigation.expand
    #    - navigation.sections
    #    - navigation.instant
    #    - navigation.instant.prefetch
    #    - navigation.instant.progress
  #    - announce.dismiss

  icon:
    logo: octicons/hubot-24
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# navigations
nav:
  - Home: index.md
  - Python:
      - Introduction to Python: python/index.md
      - Syntax: python/syntax/python-syntax.md
      - Classes and Objects: python/classes/classes-and-objects.md
      - Namespaces and Scope: python/namespaces-and-scope.md
      - Object-Oriented Programming (OOP): python/classes/object-oriented-programming.md
      - Dependency Management:
          - Poetry: python/dependency/poetry.md
  - Django:
      - Introduction to Django: django/index.md
      - Best Practices and Principles:
          - Maintainability and Extendability: django/best_practices/best_practices_and_principles.md
          - Naming View Files: django/best_practices/naming_view_files.md
          - Naming Template Files: django/best_practices/naming_template_files.md
          - gettext vs gettext_lazy: django/best_practices/gettext.md
      - Models and Databases: django/models.md
      - Internationalization: django/localize/internationalization.md
      - Reduce Test Time: django/testing/reduce-test-time.md
      - Sample Codes:
          - Sample Codes: django/sample_codes/structured_menu.md
  - Software Developing:
      - Introduction: developing/index.md
      - Git:
          - Commit Message Structure: developing/git/commit-message-structure.md
          - Best Practices for Git Commits: developing/git/best-practices-for-git-commits.md
          - Generate Commit Message with AI Assistant: developing/git/generate-commit-message-with-ai-assistant.md
      - Design Patterns: developing/design_patterns/design_patterns.md
      - SOLID Principles:
          - Intro: developing/solid_principles/solid_principles.md
          - Single Responsibility Principle: developing/solid_principles/srp.md
      - Codebase:
          - Business Logic: developing/codebase/business_logic.md
          - Modular design: developing/codebase/modular_design.md
          - Mixins vs. Utils: developing/codebase/mixins_vs_utils.md
  - Software Engineering:
      - Chapter 1 - Software and Software Engineering: engineering/chapter_1/software_and_software_engineering.md